### ISSUE TITLE
readme第一个gif 没有这个工程

### ISSUE THREAD

**Issue by wangbang79408854** [FeiGeChuanShu/ncnn_Android_face#10]

**Comment by FeiGeChuanShu** [comment]
@wangbang79408854 在这里 https://github.com/FeiGeChuanShu/ncnn_Android_face/blob/main/ncnn-android-scrfd-master/app/src/main/jni/scrfd.cpp#L461 可以自己改成seg

**Comment by wangbang79408854** [comment]
谢谢 看到了
